# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  chisel = {
    pname = "chisel";
    version = "a2b40360e3dd4e2faedad52989865ffc3a1abbdd";
    src = fetchFromGitHub {
      owner = "chipsalliance";
      repo = "chisel";
      rev = "a2b40360e3dd4e2faedad52989865ffc3a1abbdd";
      fetchSubmodules = false;
      sha256 = "sha256-w0e2GONv0wk0lGGosDfQfuKv2olRIj+FvaqwVVLXQCE=";
    };
    date = "2025-02-08";
  };
}
