# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  chisel = {
    pname = "chisel";
    version = "7b029eed5c6fef3d06155de6aa82deb8b9ac2288";
    src = fetchFromGitHub {
      owner = "chipsalliance";
      repo = "chisel";
      rev = "7b029eed5c6fef3d06155de6aa82deb8b9ac2288";
      fetchSubmodules = false;
      sha256 = "sha256-y6gqMusOS711r2iyTHTno6Wzt7mkY9jE+SO7RAqG6YE=";
    };
    date = "2025-02-20";
  };
}
