# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  chisel = {
    pname = "chisel";
    version = "aab42b25f87c06ffca50cafe827237c46e667169";
    src = fetchFromGitHub {
      owner = "chipsalliance";
      repo = "chisel";
      rev = "aab42b25f87c06ffca50cafe827237c46e667169";
      fetchSubmodules = false;
      sha256 = "sha256-v4bevmSBCEVBjns7ZCSpKZBbACaOspahsB+ZX5OpCxE=";
    };
    date = "2025-02-23";
  };
}
